//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Date_Time_Application.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Date_Time_Application.resources.IndexTexts", typeof(IndexTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add days to the Date.
        /// </summary>
        public static string Add_days_to_the_Date {
            get {
                return ResourceManager.GetString("Add days to the Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the day of the Week.
        /// </summary>
        public static string Find_the_day_of_the_Week {
            get {
                return ResourceManager.GetString("Find the day of the Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the weeknumber.
        /// </summary>
        public static string Find_the_weeknumber {
            get {
                return ResourceManager.GetString("Find the weeknumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the choice.
        /// </summary>
        public static string Select_the_choice {
            get {
                return ResourceManager.GetString("Select the choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract 2 Dates.
        /// </summary>
        public static string Subtract_2_Dates {
            get {
                return ResourceManager.GetString("Subtract 2 Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate the NLP.
        /// </summary>
        public static string Translate_the_NLP {
            get {
                return ResourceManager.GetString("Translate the NLP", resourceCulture);
            }
        }
    }
}
